// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XmlApp.Data;

#nullable disable

namespace XmlApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241013141156_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("XmlApp.Models.Fields.Fatura", b =>
                {
                    b.Property<string>("FaturaNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FaturaParaBirimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaturaTarih")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaturaTeslimSekli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaturaTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FaturaTutari")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KarsiFirmaBilgisiAdiUnvani")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OdemeSekli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeslimAdresiAdiTicaretUnvani")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FaturaNo");

                    b.HasIndex("KarsiFirmaBilgisiAdiUnvani");

                    b.HasIndex("TeslimAdresiAdiTicaretUnvani");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.FaturaBilgileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FaturaNo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FaturaNo");

                    b.ToTable("FaturaBilgileri");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.FonDekont", b =>
                {
                    b.Property<string>("FonDekontDekontNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("FonDekontKullanilan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FonDekontKullanilanDolar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FonDekontKullanilanPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FonDekontTarih")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FonDekontTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FonDekontTutarPB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FonDekontDekontNo");

                    b.ToTable("FonDekont");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.GenelBilgiler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BelgeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepoKullanimBelgeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DepoKullanimBelgeliFirma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisReferansNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaFaaliyetRuhsatiKonusu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaFaaliyetRuhsatiNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaTelefonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaTicaretUnvani")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormuDolduraninAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GumrukId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KayitTarihi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerbestBolgeAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SevkiyatSekliAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SevkiyatSekliAdi");

                    b.ToTable("GenelBilgiler");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.IslemKonusuBilgileri", b =>
                {
                    b.Property<string>("IslemKonusu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IslemKonusuTicari")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IslemKonusuTicariOlmayan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("IslemKonusuBilgileri");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.IslemTuruBilgileri", b =>
                {
                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("IslemTuruBilgileri");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.IslemYonuBilgileri", b =>
                {
                    b.Property<string>("IslemYonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("IslemYonuBilgileri");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.KarsiFirmaBilgisi", b =>
                {
                    b.Property<string>("AdiUnvani")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faks1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faks2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostaKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VergiKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdiUnvani");

                    b.ToTable("KarsiFirmaBilgileri", (string)null);
                });

            modelBuilder.Entity("XmlApp.Models.Fields.MalKalem", b =>
                {
                    b.Property<string>("MalKalemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BirinciBirim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BirinciMiktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BrutAgirlik")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cins")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeldigiGidecegiUlke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GumrukSiraNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KapAdedi")
                        .HasColumnType("int");

                    b.Property<string>("KapTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MalBedeli")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MalBedeliParaBirimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MalKalemBilgileriId")
                        .HasColumnType("int");

                    b.Property<string>("MalKalemTeslimSekli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mensei")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NavlunBedeli")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NavlunBedeliParaBirimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SigortaBedeli")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SigortaBedeliParaBirimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiraNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gtip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MalKalemId");

                    b.HasIndex("MalKalemBilgileriId");

                    b.ToTable("MalKalemler");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.MalKalemBilgileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MalKalemUsdToplami")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("MalKalemBilgileri");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.SBIFBilgileri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FaturaBilgileriId")
                        .HasColumnType("int");

                    b.Property<int>("GenelBilgilerId")
                        .HasColumnType("int");

                    b.Property<int>("MalKalemBilgileriId")
                        .HasColumnType("int");

                    b.Property<int>("SbifBilgiFisiId")
                        .HasColumnType("int");

                    b.Property<int>("TalepEdilenIsleticiHizmetleriId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FaturaBilgileriId");

                    b.HasIndex("GenelBilgilerId");

                    b.HasIndex("MalKalemBilgileriId");

                    b.HasIndex("SbifBilgiFisiId");

                    b.HasIndex("TalepEdilenIsleticiHizmetleriId");

                    b.ToTable("SBIFBilgileri");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.SbifBilgiFisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FonDekontDekontNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FonDekontDekontNo");

                    b.ToTable("SbifBilgiFisi");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.SevkiyatSekli", b =>
                {
                    b.Property<string>("SevkiyatSekliAdi")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SevkiyatSekliAdi");

                    b.ToTable("SevkiyatSekli", (string)null);
                });

            modelBuilder.Entity("XmlApp.Models.Fields.TalepEdilenIsleticiHizmetleri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DigerTalepEdilenHizmetler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ellecleme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsMakinasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kantar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KoordinasyonHizmeti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrtakDepo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YuklemeBosaltma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TalepEdilenIsleticiHizmetleri");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.TeslimAdresi", b =>
                {
                    b.Property<string>("AdiTicaretUnvani")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Adresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faks1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Faks2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostaKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ulke")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdiTicaretUnvani");

                    b.ToTable("TeslimAdresi", (string)null);
                });

            modelBuilder.Entity("XmlApp.Models.Fields.Fatura", b =>
                {
                    b.HasOne("XmlApp.Models.Fields.KarsiFirmaBilgisi", "KarsiFirmaBilgisi")
                        .WithMany()
                        .HasForeignKey("KarsiFirmaBilgisiAdiUnvani")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XmlApp.Models.Fields.TeslimAdresi", "TeslimAdresi")
                        .WithMany()
                        .HasForeignKey("TeslimAdresiAdiTicaretUnvani")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KarsiFirmaBilgisi");

                    b.Navigation("TeslimAdresi");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.FaturaBilgileri", b =>
                {
                    b.HasOne("XmlApp.Models.Fields.Fatura", "Fatura")
                        .WithMany()
                        .HasForeignKey("FaturaNo");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.GenelBilgiler", b =>
                {
                    b.HasOne("XmlApp.Models.Fields.SevkiyatSekli", "SevkiyatSekli")
                        .WithMany()
                        .HasForeignKey("SevkiyatSekliAdi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SevkiyatSekli");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.MalKalem", b =>
                {
                    b.HasOne("XmlApp.Models.Fields.MalKalemBilgileri", null)
                        .WithMany("MalKalem")
                        .HasForeignKey("MalKalemBilgileriId");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.SBIFBilgileri", b =>
                {
                    b.HasOne("XmlApp.Models.Fields.FaturaBilgileri", "FaturaBilgileri")
                        .WithMany()
                        .HasForeignKey("FaturaBilgileriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XmlApp.Models.Fields.GenelBilgiler", "GenelBilgiler")
                        .WithMany()
                        .HasForeignKey("GenelBilgilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XmlApp.Models.Fields.MalKalemBilgileri", "MalKalemBilgileri")
                        .WithMany()
                        .HasForeignKey("MalKalemBilgileriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XmlApp.Models.Fields.SbifBilgiFisi", "SbifBilgiFisi")
                        .WithMany()
                        .HasForeignKey("SbifBilgiFisiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XmlApp.Models.Fields.TalepEdilenIsleticiHizmetleri", "TalepEdilenIsleticiHizmetleri")
                        .WithMany()
                        .HasForeignKey("TalepEdilenIsleticiHizmetleriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaturaBilgileri");

                    b.Navigation("GenelBilgiler");

                    b.Navigation("MalKalemBilgileri");

                    b.Navigation("SbifBilgiFisi");

                    b.Navigation("TalepEdilenIsleticiHizmetleri");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.SbifBilgiFisi", b =>
                {
                    b.HasOne("XmlApp.Models.Fields.FonDekont", "FonDekont")
                        .WithMany()
                        .HasForeignKey("FonDekontDekontNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FonDekont");
                });

            modelBuilder.Entity("XmlApp.Models.Fields.MalKalemBilgileri", b =>
                {
                    b.Navigation("MalKalem");
                });
#pragma warning restore 612, 618
        }
    }
}
